### ISSUE TITLE
net::ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by netwrkx** [goodheads/FileUpload#1]
angular.js:10514 POST http://localhost:5000/api/upload net::ERR_EMPTY_RESPONSE

**Comment by unicodeveloper** [comment]
What's the issue?

**Comment by netwrkx** [comment]
File won't upload, I got empty {} for req.body and req.files. What am i missing? I did bower install and updated on source to match latest ng-file-upload build.

**Comment by unicodeveloper** [comment]
I really don't know why you are getting that, but you can also check out this source code https://github.com/goodheads/yourtube

**Comment by netwrkx** [comment]
Why not try replicating the system and test the file upload with recent ng-file-upload build

2, there are no cloudinary path in your public files
